title: Suraj Kumar Mahto # your name (or website title) here
logo: "/profile_4.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 A highly skilled engineering professional with a Bachelor of Engineering (B.E.) in Computer Science and Technology, specializing in Information Technology, from Birla Institute of Technology (BIT) Mesra, Ranchi. 
 With 7 years of experience in developing Microservices and distributed systems, I have built a solid foundation in software engineering principles. 
 I am dedicated to staying at the cutting edge of emerging technologies and methodologies, continually advancing my expertise to deliver innovative and impactful solutions.
theme: jekyll-theme-minimal
