title: Suraj Kumar Mahto # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Strong engineering professional with a Bachelor of Engineering (B.E.) focused on Computer Science and Technology major in Information Technology from Birla Institute of Technology (BIT) Mesra Ranchi. 
 Overall 5 years of experience in the development of MicroServices and Distributed applications.
 Eager to learn new technologies and methodologies.
theme: jekyll-theme-minimal
